name: "Docker test"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        with:
          disable-auto-build-publish: false
          disable-job-summary: false
        env:
          JF_URL: ${{ vars.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JFROG_CLI_BUILD_PROJECT: proj1
          JFROF_CLI_LOG_LEVEL: DEBUG
      - name: Build Docker image
        run: |
          docker build -t iwashitah6.jfrog.io/proj1-docker-virtual/alpine:3.3 .
      - name: Scan Docker image
        run: |
          jf docker scan iwashitah6.jfrog.io/proj1-docker-virtual/alpine:3.3
          jf rt bp
